### ISSUE TITLE
Make the output of `bios get` valid YAML

### ISSUE THREAD

**Issue by dev-zero** [Cray-HPE/gru#46]
##### SUMMARY

To use the information in a Unix-type pipe-chain it would be useful if `bios get` would output valid YAML.
At the moment it does not due to log messages interlaced with the output (fixed by #44), when using IP addresses for hosts (since those are not valid YAML keys) and some keys are not quoted.

##### ISSUE TYPE
- RFE

**Comment by rustydb** [comment]
Would it be sufficient if there was a global YAML output option (similar to the JSON option)?

**Comment by rustydb** [comment]
> Would it be sufficient if there was a global YAML output option (similar to the JSON option)?

I just saw your PR, I think I can rescind my previous question given your PR satisfies the RFE you reported. A global YAML toggle would still be nice.
